data = {
  "results": [
    {
      "change_type": "UNCHANGED",
      "covered_recipient_type": "Covered Recipient Physician",
      "teaching_hospital_ccn": "",
      "teaching_hospital_id": "",
      "teaching_hospital_name": "",
      "covered_recipient_profile_id": "1357816",
      "covered_recipient_npi": "1154649267",
      "covered_recipient_first_name": "JUSTIN",
      "covered_recipient_middle_name": "",
      "covered_recipient_last_name": "MITCHELL",
      "covered_recipient_name_suffix": "",
      "recipient_primary_business_street_address_line1": "3111 GUNDERSEN DR",
      "recipient_primary_business_street_address_line2": "",
      "recipient_city": "ONALASKA",
      "recipient_state": "WI",
      "recipient_zip_code": "54650-8447",
      "recipient_country": "United States",
      "recipient_province": "",
      "recipient_postal_code": "",
      "covered_recipient_primary_type_1": "Medical Doctor",
      "covered_recipient_primary_type_2": "",
      "covered_recipient_primary_type_3": "",
      "covered_recipient_primary_type_4": "",
      "covered_recipient_primary_type_5": "",
      "covered_recipient_primary_type_6": "",
      "covered_recipient_specialty_1": "Allopathic & Osteopathic Physicians|Orthopaedic Surgery",
      "covered_recipient_specialty_2": "",
      "covered_recipient_specialty_3": "",
      "covered_recipient_specialty_4": "",
      "covered_recipient_specialty_5": "",
      "covered_recipient_specialty_6": "",
      "covered_recipient_license_state_code1": "IA",
      "covered_recipient_license_state_code2": "",
      "covered_recipient_license_state_code3": "",
      "covered_recipient_license_state_code4": "",
      "covered_recipient_license_state_code5": "",
      "submitting_applicable_manufacturer_or_applicable_gpo_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_id": "100000136408",
      "applicable_manufacturer_or_applicable_gpo_making_payment_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_state": "WI",
      "applicable_manufacturer_or_applicable_gpo_making_payment_country": "United States",
      "total_amount_of_payment_usdollars": "124.14",
      "date_of_payment": "01/22/2022",
      "number_of_payments_included_in_total_amount": "1",
      "form_of_payment_or_transfer_of_value": "In-kind items and services",
      "nature_of_payment_or_transfer_of_value": "Food and Beverage",
      "city_of_travel": "",
      "state_of_travel": "",
      "country_of_travel": "",
      "physician_ownership_indicator": "No",
      "third_party_payment_recipient_indicator": "No Third Party Payment",
      "name_of_third_party_entity_receiving_payment_or_transfer_of_ccfc": "",
      "charity_indicator": "",
      "third_party_equals_covered_recipient_indicator": "",
      "contextual_information": "Transfer of value related to products manufactured by Arthrex, Inc",
      "delay_in_publication_indicator": "No",
      "record_id": "873399573",
      "dispute_status_for_publication": "No",
      "related_product_indicator": "No",
      "covered_or_noncovered_indicator_1": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_1": "",
      "product_category_or_therapeutic_area_1": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_1": "",
      "associated_drug_or_biological_ndc_1": "",
      "associated_device_or_medical_supply_pdi_1": "",
      "covered_or_noncovered_indicator_2": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_2": "",
      "product_category_or_therapeutic_area_2": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_2": "",
      "associated_drug_or_biological_ndc_2": "",
      "associated_device_or_medical_supply_pdi_2": "",
      "covered_or_noncovered_indicator_3": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_3": "",
      "product_category_or_therapeutic_area_3": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_3": "",
      "associated_drug_or_biological_ndc_3": "",
      "associated_device_or_medical_supply_pdi_3": "",
      "covered_or_noncovered_indicator_4": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_4": "",
      "product_category_or_therapeutic_area_4": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_4": "",
      "associated_drug_or_biological_ndc_4": "",
      "associated_device_or_medical_supply_pdi_4": "",
      "covered_or_noncovered_indicator_5": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_5": "",
      "product_category_or_therapeutic_area_5": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_5": "",
      "associated_drug_or_biological_ndc_5": "",
      "associated_device_or_medical_supply_pdi_5": "",
      "program_year": "2022",
      "payment_publication_date": "01/18/2024"
    },
    {
      "change_type": "UNCHANGED",
      "covered_recipient_type": "Covered Recipient Physician",
      "teaching_hospital_ccn": "",
      "teaching_hospital_id": "",
      "teaching_hospital_name": "",
      "covered_recipient_profile_id": "1358188",
      "covered_recipient_npi": "1588059265",
      "covered_recipient_first_name": "RAVI",
      "covered_recipient_middle_name": "",
      "covered_recipient_last_name": "PATEL",
      "covered_recipient_name_suffix": "",
      "recipient_primary_business_street_address_line1": "420 N IL ROUTE 31",
      "recipient_primary_business_street_address_line2": "",
      "recipient_city": "CRYSTAL LAKE",
      "recipient_state": "IL",
      "recipient_zip_code": "60012-3709",
      "recipient_country": "United States",
      "recipient_province": "",
      "recipient_postal_code": "",
      "covered_recipient_primary_type_1": "Medical Doctor",
      "covered_recipient_primary_type_2": "",
      "covered_recipient_primary_type_3": "",
      "covered_recipient_primary_type_4": "",
      "covered_recipient_primary_type_5": "",
      "covered_recipient_primary_type_6": "",
      "covered_recipient_specialty_1": "Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Sports Medicine",
      "covered_recipient_specialty_2": "",
      "covered_recipient_specialty_3": "",
      "covered_recipient_specialty_4": "",
      "covered_recipient_specialty_5": "",
      "covered_recipient_specialty_6": "",
      "covered_recipient_license_state_code1": "IL",
      "covered_recipient_license_state_code2": "",
      "covered_recipient_license_state_code3": "",
      "covered_recipient_license_state_code4": "",
      "covered_recipient_license_state_code5": "",
      "submitting_applicable_manufacturer_or_applicable_gpo_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_id": "100000136408",
      "applicable_manufacturer_or_applicable_gpo_making_payment_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_state": "WI",
      "applicable_manufacturer_or_applicable_gpo_making_payment_country": "United States",
      "total_amount_of_payment_usdollars": "1200.00",
      "date_of_payment": "09/06/2022",
      "number_of_payments_included_in_total_amount": "1",
      "form_of_payment_or_transfer_of_value": "In-kind items and services",
      "nature_of_payment_or_transfer_of_value": "Education",
      "city_of_travel": "",
      "state_of_travel": "",
      "country_of_travel": "",
      "physician_ownership_indicator": "No",
      "third_party_payment_recipient_indicator": "No Third Party Payment",
      "name_of_third_party_entity_receiving_payment_or_transfer_of_ccfc": "",
      "charity_indicator": "",
      "third_party_equals_covered_recipient_indicator": "",
      "contextual_information": "Transfer of value related to products manufactured by Arthrex, Inc",
      "delay_in_publication_indicator": "No",
      "record_id": "873399577",
      "dispute_status_for_publication": "No",
      "related_product_indicator": "No",
      "covered_or_noncovered_indicator_1": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_1": "",
      "product_category_or_therapeutic_area_1": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_1": "",
      "associated_drug_or_biological_ndc_1": "",
      "associated_device_or_medical_supply_pdi_1": "",
      "covered_or_noncovered_indicator_2": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_2": "",
      "product_category_or_therapeutic_area_2": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_2": "",
      "associated_drug_or_biological_ndc_2": "",
      "associated_device_or_medical_supply_pdi_2": "",
      "covered_or_noncovered_indicator_3": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_3": "",
      "product_category_or_therapeutic_area_3": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_3": "",
      "associated_drug_or_biological_ndc_3": "",
      "associated_device_or_medical_supply_pdi_3": "",
      "covered_or_noncovered_indicator_4": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_4": "",
      "product_category_or_therapeutic_area_4": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_4": "",
      "associated_drug_or_biological_ndc_4": "",
      "associated_device_or_medical_supply_pdi_4": "",
      "covered_or_noncovered_indicator_5": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_5": "",
      "product_category_or_therapeutic_area_5": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_5": "",
      "associated_drug_or_biological_ndc_5": "",
      "associated_device_or_medical_supply_pdi_5": "",
      "program_year": "2022",
      "payment_publication_date": "01/18/2024"
    },
    {
      "change_type": "UNCHANGED",
      "covered_recipient_type": "Covered Recipient Physician",
      "teaching_hospital_ccn": "",
      "teaching_hospital_id": "",
      "teaching_hospital_name": "",
      "covered_recipient_profile_id": "1358188",
      "covered_recipient_npi": "1588059265",
      "covered_recipient_first_name": "RAVI",
      "covered_recipient_middle_name": "",
      "covered_recipient_last_name": "PATEL",
      "covered_recipient_name_suffix": "",
      "recipient_primary_business_street_address_line1": "420 N IL ROUTE 31",
      "recipient_primary_business_street_address_line2": "",
      "recipient_city": "CRYSTAL LAKE",
      "recipient_state": "IL",
      "recipient_zip_code": "60012-3709",
      "recipient_country": "United States",
      "recipient_province": "",
      "recipient_postal_code": "",
      "covered_recipient_primary_type_1": "Medical Doctor",
      "covered_recipient_primary_type_2": "",
      "covered_recipient_primary_type_3": "",
      "covered_recipient_primary_type_4": "",
      "covered_recipient_primary_type_5": "",
      "covered_recipient_primary_type_6": "",
      "covered_recipient_specialty_1": "Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Sports Medicine",
      "covered_recipient_specialty_2": "",
      "covered_recipient_specialty_3": "",
      "covered_recipient_specialty_4": "",
      "covered_recipient_specialty_5": "",
      "covered_recipient_specialty_6": "",
      "covered_recipient_license_state_code1": "IL",
      "covered_recipient_license_state_code2": "",
      "covered_recipient_license_state_code3": "",
      "covered_recipient_license_state_code4": "",
      "covered_recipient_license_state_code5": "",
      "submitting_applicable_manufacturer_or_applicable_gpo_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_id": "100000136408",
      "applicable_manufacturer_or_applicable_gpo_making_payment_name": "Great Lakes Orthopedics",
      "applicable_manufacturer_or_applicable_gpo_making_payment_state": "WI",
      "applicable_manufacturer_or_applicable_gpo_making_payment_country": "United States",
      "total_amount_of_payment_usdollars": "7.46",
      "date_of_payment": "09/06/2022",
      "number_of_payments_included_in_total_amount": "1",
      "form_of_payment_or_transfer_of_value": "In-kind items and services",
      "nature_of_payment_or_transfer_of_value": "Food and Beverage",
      "city_of_travel": "",
      "state_of_travel": "",
      "country_of_travel": "",
      "physician_ownership_indicator": "No",
      "third_party_payment_recipient_indicator": "No Third Party Payment",
      "name_of_third_party_entity_receiving_payment_or_transfer_of_ccfc": "",
      "charity_indicator": "",
      "third_party_equals_covered_recipient_indicator": "",
      "contextual_information": "Transfer of value related to products manufactured by Arthrex, Inc",
      "delay_in_publication_indicator": "No",
      "record_id": "873399579",
      "dispute_status_for_publication": "No",
      "related_product_indicator": "No",
      "covered_or_noncovered_indicator_1": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_1": "",
      "product_category_or_therapeutic_area_1": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_1": "",
      "associated_drug_or_biological_ndc_1": "",
      "associated_device_or_medical_supply_pdi_1": "",
      "covered_or_noncovered_indicator_2": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_2": "",
      "product_category_or_therapeutic_area_2": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_2": "",
      "associated_drug_or_biological_ndc_2": "",
      "associated_device_or_medical_supply_pdi_2": "",
      "covered_or_noncovered_indicator_3": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_3": "",
      "product_category_or_therapeutic_area_3": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_3": "",
      "associated_drug_or_biological_ndc_3": "",
      "associated_device_or_medical_supply_pdi_3": "",
      "covered_or_noncovered_indicator_4": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_4": "",
      "product_category_or_therapeutic_area_4": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_4": "",
      "associated_drug_or_biological_ndc_4": "",
      "associated_device_or_medical_supply_pdi_4": "",
      "covered_or_noncovered_indicator_5": "",
      "indicate_drug_or_biological_or_device_or_medical_supply_5": "",
      "product_category_or_therapeutic_area_5": "",
      "name_of_drug_or_biological_or_device_or_medical_supply_5": "",
      "associated_drug_or_biological_ndc_5": "",
      "associated_device_or_medical_supply_pdi_5": "",
      "program_year": "2022",
      "payment_publication_date": "01/18/2024"
    }
  ]
}