# Generated by Django 5.0.2 on 2024-02-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_profile_id', models.IntegerField()),
                ('doctor_npi', models.IntegerField()),
                ('doctor_first_name', models.CharField(max_length=50)),
                ('doctor_middle_name', models.CharField(max_length=50)),
                ('doctor_last_name', models.CharField(max_length=50)),
                ('doctor_primary_address_line1', models.CharField()),
                ('doctor_primary_address_line2', models.CharField()),
                ('doctor_city', models.CharField(max_length=50)),
                ('doctor_state', models.CharField(max_length=2)),
                ('doctor_zip_code', models.CharField(max_length=10)),
                ('doctor_country', models.CharField(max_length=50)),
                ('doctor_primary_type', models.CharField()),
                ('doctor_specialty', models.CharField()),
                ('doctor_license_state_code', models.CharField(max_length=2)),
                ('submitting_manufacturer_name', models.CharField()),
                ('submitting_manufacturer_id', models.IntegerField()),
                ('submitting_manufacturer_state', models.CharField(max_length=2)),
                ('submitting_manufacturer_country', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_quantity', models.IntegerField()),
                ('payment_type', models.CharField()),
                ('program_year', models.IntegerField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
