# Generated by Django 5.0.3 on 2024-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_payment_doctor_npi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_year', models.IntegerField(default=2022)),
                ('identifier', models.CharField()),
                ('modified', models.DateField()),
            ],
        ),
    ]
