# Generated by Django 5.0.3 on 2024-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='name',
            field=models.CharField(default='Main'),
        ),
    ]
